=== DanisAvko/xml/dtd/lesson1_task3.dtd
<!--ELEMENTS-->
<!ELEMENT content (mouses, meta)>
<!ELEMENT meta (img)>
<!ELEMENT img (EMPTY)>
<!ELEMENT mouses (mouse*)>
<!ELEMENT mouse (titles, characteristic, manufacturers)>

<!ELEMENT titles (title+)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT characteristic (connection-types?, connection-interfaces?)>
<!ELEMENT connection-types (connection-type+)>
<!ELEMENT connection-interfaces (connection-interface+)>

<!ELEMENT manufacturers (manufacturer+)>
<!ELEMENT manufacturer (#PCDATA)>

<!ELEMENT connection-type (#PCDATA)>
<!ELEMENT connection-interface (#PCDATA)>

<!--ATTS-->
<!ATTLIST mouse
    id CDATA#REQUIRED
>
<!ATTLIST title
    data-id CDATA#REQUIRED
>
<!ATTLIST connection-type
    data-id CDATA#REQUIRED
>
<!ATTLIST connection-interface
    data-id CDATA#REQUIRED
    ref CDATA#REQUIRED
>
<!ATTLIST manufacturer
    data-id CDATA#REQUIRED
    officialUrl CDATA#PCDATA
>
<!ATTLIST img
    height CDATA#REQUIRED
    width CDATA#REQUIRED
    alt CDATA#REQUIRED
    src CDATA#REQUIRED
>

=== DanisAvko/xml/lesson1_task3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mouses SYSTEM "../dtd/lesson1_task3.dtd">
<!--Лучшее ХЕМЕЭЛЬ Описание комп мышек-->
<mouses>
    <mouse id="1">
        <titles>
            <title data-id="1">Шариковая</title>
            <title data-id="2">Механическая</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="1">PC/2</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Sven</manufacturer>
            <manufacturer data-id="2">Konoos</manufacturer>
            <manufacturer data-id="3">Perfeo</manufacturer>
            <manufacturer data-id="4">Marvo</manufacturer>
            <manufacturer data-id="5">Genius</manufacturer>
        </manufacturers>
    </mouse>
    <mouse id="2">
        <titles>
            <title data-id="1">Светодиодная</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
                <connection-type data-id="2">Нет провода</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="2">Bluetooth</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Sven</manufacturer>
            <manufacturer data-id="2">Konoos</manufacturer>
            <manufacturer data-id="3">Defender</manufacturer>
            <manufacturer data-id="4">Marvo</manufacturer>
            <manufacturer data-id="5">Logitech</manufacturer>
            <manufacturer data-id="6">A4tech</manufacturer>
        </manufacturers>
    </mouse>
    <mouse id="3">
        <titles>
            <title data-id="1">Лазерная</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
                <connection-type data-id="2">Нет провода</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="2">Bluetooth</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Sven</manufacturer>
            <manufacturer data-id="2">Konoos</manufacturer>
            <manufacturer data-id="3">Defender</manufacturer>
            <manufacturer data-id="4">Marvo</manufacturer>
            <manufacturer data-id="5">Gamdias</manufacturer>
        </manufacturers>
    </mouse>
    <mouse id="4">
        <titles>
            <title data-id="1">Трекбол</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="1">PC/2</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Sven</manufacturer>
            <manufacturer data-id="2">Konoos</manufacturer>
            <manufacturer data-id="3">Defender</manufacturer>
            <manufacturer data-id="4">Marvo</manufacturer>
            <manufacturer data-id="5">Gamdias</manufacturer>
        </manufacturers>
    </mouse>
    <mouse id="5">
        <titles>
            <title data-id="1">Индукционная</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="1">PC/2</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Sven</manufacturer>
            <manufacturer data-id="2">Marvo</manufacturer>
            <manufacturer data-id="3">Gamdias</manufacturer>
        </manufacturers>
    </mouse>
    <mouse id="6">
        <titles>
            <title data-id="1">Гироскопическая</title>
        </titles>
        <characteristic>
            <connection-types>
                <connection-type data-id="1">Провод</connection-type>
                <connection-type data-id="2">Нет провода</connection-type>
            </connection-types>
            <connection-interfaces>
                <connection-interface data-id="1" ref="1">USB</connection-interface>
                <connection-interface data-id="2" ref="1">PC/2</connection-interface>
                <connection-interface data-id="3" ref="2">Bluetooth</connection-interface>
            </connection-interfaces>
        </characteristic>
        <manufacturers>
            <manufacturer data-id="1">Defender</manufacturer>
            <manufacturer data-id="2">Marvo</manufacturer>
            <manufacturer data-id="3">Gamdias</manufacturer>
        </manufacturers>
    </mouse>
</mouses>
